apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-test-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/HCMUS-DevOps-Projects/project02-k8s.git'
    targetRevision: loki
    path: argocd-apps/loki
    helm:
      valueFiles:
        - 'loki-values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true