apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-test-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: false

        promtail:
          enabled: true
          config:
            snippets:
              pipelineStages:
                - cri: {}
                - regex:
                    expression: '.*\[(?P<app_name>.*),(?P<trace_id>[a-f0-9-]*),(?P<span_id>[a-f0-9-]*)\].*'
                - labels:
                    app: app_name
                    traceID: trace_id
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true