# File để deploy môi trường thử nghiệm cho nhánh loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-loki-review
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/HCMUS-DevOps-Projects/project02-k8s.git' 
    targetRevision: loki
    path: .
    helm:
      valueFiles:
      - environments/loki-review/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      